version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 6969:6969
    volumes:
      - ./src/utils:/usr/src/app/src/utils
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    restart: always
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 6381:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: